### ISSUE TITLE
resizing

### ISSUE THREAD

**Issue by gedw99** [J-Siu/go-png2ico#5]
logo.png(1200x900): Width and height cannot be larger than 256.

are you interested in adding resizing ?

**Comment by J-Siu** [comment]
Let me double check.

**Comment by J-Siu** [comment]
@gedw99 PNG size can be over 256 according to https://en.wikipedia.org/wiki/ICO_(file_format)#cite_note-bigSize-7

Following is the quote:

> Since Windows 95 size of an image in the ICONDIRENTRY structure might be set to zero which means 256 pixels. Since Windows Vista the size of an image is inferred from the BITMAPINFOHEADER structure or PNG image data which allows storing icons with sizes more than 256.

Row 1 and 2 of `ICONDIRENTRY structure` table in the same page mention the same.

However I have to double check my code, because ICONDIRENTRY structure offset 0(width) and 1(height) should be set to 0 if the respective PNG dimension is 256 or higher.

**Comment by gedw99** [comment]
Thanks @J-Siu 

let me know what you discover.

if you need help just shout

**Comment by J-Siu** [comment]
@gedw99 I updated the code to allow PNG with width, height >= 256. Please me know if that work for you.

Regarding resizing, thought there are some golang library out there, I properly won't add it as that are too much variables doing that.

**Comment by gedw99** [comment]
Yeah no point .

this will work for me.

thsnks dude !

**Comment by gedw99** [comment]
@J-Siu thanks works great.

even handles png with alpha channels to produce an ico with alpha channels.

nice work ...
